---
driver:
  name: vagrant

platforms:
  - name: debian/jessie64
  - name: ubuntu/xenial64
  - name: centos/7
  - name: centos/6

provisioner:
  name: salt_solo
  salt_version: '2016.3'
  # data_path: test/shared
  is_file_root: true
  pillars:
    top.sls:
      base:
        '*':
          - bareos
    bareos.sls:
      bareos:
        use_upstream_repo: true

suites:
  - name: bareos
    provisioner:
      state_top:
        base:
          '*':
            - bareos.filedaemon
