---
driver:
  name: vagrant
  cachier: true
  cpus: 2

platforms:
  - name: bento/debian-8
  - name: bento/ubuntu-16.04
  - name: bento/centos-6
  - name: bento/centos-7

provisioner:
  name: salt_solo
  log_level: info
  require_chef: false
  salt_version: latest
  formula: bareos
  pillars:
    top.sls:
      base:
        '*':
          - bareos
    bareos.sls:
      bareos:
        use_upstream_repo: true
        director:
          database:
            manage: true

verifier:
  name: inspec
  sudo: true

suites:
  - name: bareos-postgresql
    provisioner:
      dependencies:
        - name: postgres
          repo: git
          source: https://github.com/saltstack-formulas/postgres-formula.git
      pillars:
        bareos.sls:
          bareos:
            director:
              database:
                backend: postgresql
      state_top:
        base:
          '*':
            - postgres
            - bareos

  - name: bareos-mysql
    provisioner:
      dependencies:
        - name: mysql
          repo: git
          source: https://github.com/saltstack-formulas/mysql-formula.git
      pillars:
        bareos.sls:
          mysql:
            server:
              root_password: ''
          bareos:
            director:
              database:
                backend: mysql
      state_top:
        base:
          '*':
            - mysql
            - bareos
